#!/bin/bash

echo "🔧 Setting up Ukubona Wiki Structure..."

# Step 1: Create virtual environment
echo "📦 Creating virtual environment..."
python3 -m venv venv

# Step 2: Activate environment
echo "✅ Activating environment..."
source venv/bin/activate

# Step 3: Install any required packages (none needed now)
echo "📥 No external packages needed at this time."

# Step 4: Create the Python script dynamically
echo "📄 Writing generate_wiki_structure.py..."
cat << 'EOF' > generate_wiki_structure.py
import os
import random

root_dir = "ukubona-wiki"

structure = {
    "": ["index.html"],
    "style": ["article.css", "settings-bar.css"],
    "js": ["toggle-darkmode.js", "wiki-controls.js", "lightbox.js"],
    "images": [
        "favicon-light.ico", "favicon-dark.ico", "ukubona-light.png",
        "ukubona-dark.png", "fractal.png", "da_capo.png",
        "im-swimming.jpeg", "swimming-fractal.jpeg"
    ],
    "includes": [
        "head.html", "header.html", "footer.html", "toc.html",
        "title.html", "infobox.html", "settings-bar.html",
        "lightbox.html", "version-timeline.html"
    ],
    "sections": [
        "introduction.html", "bet-david-grammar.html", "fractal-metabolism.html",
        "prosody-grammar.html", "visualizing-fractal.html", "philosophical-implications.html",
        "ukubona-core.html", "conclusion.html", "see-also.html", "acknowledgments.html"
    ],
    "pages": [
        "epistemic-topology.md", "fractal-grammar.md", "im-swimming.md", "neuro-symbolic.md",
        "cingulo-insular.html", "determined.html", "noise-signal.html", "salience.html",
        "turtles.html", "maga-vs-science.html", "matrix.html", "tyler-perry.html",
        "chat-with-gpt.html", "consent.html", "sapolsky.html", "babyface.html", "ukuvela.html",
        "dolphin.html", "false-positive.html", "alchemy.html", "internship.html", "yoda.html",
        "gospel.html", "fena.html", "faux-physics.html", "fraud.html", "decision-making.html"
    ]
}

html_comments = [
    "<!-- Generated by Ukubona Wiki Engine -->",
    "<!-- fractal recursion begins -->",
    "<!-- echo of a deeper signal -->",
    "<!-- illusion of agency -->",
    "<!-- part of the pentadic flow -->"
]

code_comments = [
    "# auto-generated stylesheet",
    "# controls UI behavior",
    "# fractal simulation module",
    "# Ukubona system generated",
    "# dopamine recursion script"
]

def random_comment(filename):
    if filename.endswith((".html", ".md")):
        return random.choice(html_comments)
    elif filename.endswith((".js", ".css", ".py")):
        return random.choice(code_comments)
    else:
        return ""

for subdir, files in structure.items():
    dir_path = os.path.join(root_dir, subdir)
    os.makedirs(dir_path, exist_ok=True)
    for filename in files:
        file_path = os.path.join(dir_path, filename)
        content = random_comment(filename) + "\n" if random_comment(filename) else ""
        mode = "w" if not filename.endswith((".ico", ".png", ".jpeg")) else "wb"
        with open(file_path, mode) as f:
            if mode == "w":
                f.write(content)
            else:
                f.write(os.urandom(64))

print(f"📁 '{root_dir}' structure created with placeholder files and random comments.")
EOF

# Step 5: Run the Python script
echo "🚀 Running generate_wiki_structure.py..."
python generate_wiki_structure.py

# Step 6: Deactivate environment
echo "🛑 Deactivating virtual environment."
deactivate

echo "✅ Setup complete. You can now explore 'ukubona-wiki/'"

